mex -v ../KMAP_mex_files/kfit_srtm_mex.cpp ...
    ../KMAP_source_files/kinlib_common.cpp ...
    ../KMAP_source_files/kinlib_models.cpp ...
    ../KMAP_source_files/kinlib_optimization.cpp ...
    -I../KMAP_source_files/ ...
    CXXFLAGS='$CXXFLAGS -fopenmp' ...
    LDFLAGS='$LDFLAGS -fopenmp'